### ISSUE TITLE
Change module system to node in flowconfig

### ISSUE THREAD

**Issue by rpivo** [klarna/higher-order-components#85]
It looks like the Haste module system is deprecated, and also specific to React Native. https://github.com/facebookarchive/node-haste

Maybe the module system in the flow config should be changed to node?

**Comment by xaviervia** [comment]
Hi @rpivo , thanks for the suggestion.

Unfortunately this project will not be maintained anymore. Since the introduction of Hooks, we have  moved away from higher-order components as an approach for React. Instead, we are using [`refun`](https://www.npmjs.com/package/refun)

To compound this, the library that this repository relied upon for testing and building ([`sagui`](https://www.npmjs.com/package/sagui)) has been deprecated and it is not possible to update the  pieces that it interoperates with without breaking entirely from it and adding a new build system, which is too much of an effort for a deprecated project. 

I will mark this project as archived and add a note to avoid confusion in the future.
